#' @include indRop.R
NULL

#' Import indRop processed data
#'
#' \code{readIndrop} takes a (vector of) file-path(s) that point to .tsv files
#' that were the output of indrops pre-processing pipeline (python package). 
#'
#' @param paths File paths (one or more) to .tsv files generated by indrops analyses
#' @param whichFile = FALSE Vector that corresponds to which files each cell came from
#'
#' @return Minimally, a sparse matrix that can be used for Seurat. May be contained
#' inside an S3 object if other parameters are set to TRUE 
#' @import Matrix
#' @import data.table
#' @examples
#' 

#' @export
setGeneric(name = "readIndrop", def = function(paths, whichFile = FALSE)
    standardGeneric("readIndrop"))

#' @rdname readIndrop
setMethod("readIndrop", signature("character", "ANY"),
          definition = function(paths, whichFile = FALSE) {

          stopifnot(method %in% c("euclidean", "pearson"))
          
})


#' Export data into three files similar to that of 10X pre-processing
#'
#' \code{export10X} takes a sparse matrix and then
#' exports the object into the files that 10X data typically comes in. 
#'
#' @param obj A sparse matrix object to be exported
#' @param folder Which folder should the data be exported to
#'
#' @return Nothing; just text saying that it was successful or not. 
#' This function wil write files to the disk though. 
#' 
#' @import Matrix
#' @examples
#' 

#' @export
setGeneric(name = "export10X", def = function(obj, folder)
    standardGeneric("export10X"))

#' @rdname export10X
setMethod("export10X", signature("ANY", "character"),
          definition = function(obj, folder) {
          
          # https://stackoverflow.com/questions/4216753/check-existence-of-directory-and-create-if-doesnt-exist
          dir.create(file.path(folder), showWarnings = FALSE)
            
          
})
